version: '2'
services:
  two_factor_auth-app:
    image: two_factor_auth
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://two_factor_auth-postgresql:5432/two_factor_auth
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  two_factor_auth-postgresql:
    extends:
      file: postgresql.yml
      service: two_factor_auth-postgresql
