version: '2'
services:
  two_factor_auth-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/two_factor_auth/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=two_factor_auth
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
